### ISSUE TITLE
Enable sandbox config

### ISSUE THREAD

**Issue by zefhemel** [zefhemel/matterless#19]
Example config 

# Sandbox
```yaml
base_image: myaccount/better-image
max_run_time: 60
cleanup_time: 120
```
